# name: Deploy to AWS Elastic Beanstalk

# on:
#   push:
#     branches: [ main, master ]
#   pull_request:
#     branches: [ main, master ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci

#     - name: Run tests (if you have any)
#       run: npm test --if-present

#     - name: Generate deployment package
#       run: zip -r deploy.zip . -x '*.git*' 'node_modules/*' '.env*' '*.log'

#     - name: Deploy to EB
#       uses: einaregilsson/beanstalk-deploy@v21
#       with:
#         aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         application_name: cargo360-api
#         environment_name: cargo360-api-prod
#         version_label: ${{ github.sha }}
#         region: us-east-1
#         deployment_package: deploy.zip
#         wait_for_environment_recovery: 300
